require("neovim.remap")
require("neovim.set")
require("neovim.globalfunc")

spec("neovim.telescope")
spec("neovim.undotree")
spec("neovim.lualine")
spec("neovim.comment")
spec("neovim.mason")
spec("neovim.formatting")
spec("neovim.trouble")
-- spec("neovim.nvim_lint")
spec("neovim.lspconfig")
spec("neovim.nvim-cmp")
spec("neovim.rust_formatting")
spec("neovim.midnight_col")
spec("neovim.multi-cursor")
spec("neovim.terminal")
spec("neovim.code-runner")
spec("neovim.bufferline")
spec("neovim.autopair")
spec("neovim.git")
spec("neovim.dressing")
spec("neovim.vim-surround")
spec("neovim.treesitter")
spec("neovim.wilder")
spec("neovim.todo")
spec("neovim.vim-illuminate")
spec("neovim.nvim-dap")

require("neovim.lazy")
